-- MySQL Script generated by MySQL Workbench
-- Mon Jan 16 16:59:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema delivery_services
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `delivery_services` ;

-- -----------------------------------------------------
-- Schema delivery_services
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `delivery_services` DEFAULT CHARACTER SET utf8 ;
USE `delivery_services` ;

-- -----------------------------------------------------
-- Table `delivery_services`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery_services`.`countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `delivery_services`.`regions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery_services`.`regions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `countries_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_regions_countries1`
    FOREIGN KEY (`countries_id`)
    REFERENCES `delivery_services`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `delivery_services`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery_services`.`cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `regions_id` INT NOT NULL,
  PRIMARY KEY (`id`),  
  CONSTRAINT `fk_cities_regions1`
    FOREIGN KEY (`regions_id`)
    REFERENCES `delivery_services`.`regions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `delivery_services`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery_services`.`addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NOT NULL,
  `cities_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_addresses_cities1`
    FOREIGN KEY (`cities_id`)
    REFERENCES `delivery_services`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `delivery_services`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery_services`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `addresses_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_users_addresses`
    FOREIGN KEY (`addresses_id`)
    REFERENCES `delivery_services`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `delivery_services`.`deliverers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery_services`.`deliverers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `rating` DECIMAL NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `delivery_services`.`vehicles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery_services`.`vehicles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) NOT NULL,
  `number` INT NOT NULL,
  `size` VARCHAR(45) NOT NULL,
  `deliverers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_vehicles_deliverers1`
    FOREIGN KEY (`deliverers_id`)
    REFERENCES `delivery_services`.`deliverers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `delivery_services`.`licenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery_services`.`licenses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  `exp_date` DATE NULL,
  `deliverers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_licenses_deliverers1`
    FOREIGN KEY (`deliverers_id`)
    REFERENCES `delivery_services`.`deliverers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `delivery_services`.`packages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery_services`.`packages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `size` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_packages_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `delivery_services`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `delivery_services`.`deliveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery_services`.`deliveries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cost` DECIMAL NOT NULL,
  `packages_id` INT NOT NULL,
  `deliverers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_deliveries_packages1`
    FOREIGN KEY (`packages_id`)
    REFERENCES `delivery_services`.`packages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_deliveries_deliverers1`
    FOREIGN KEY (`deliverers_id`)
    REFERENCES `delivery_services`.`deliverers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
